import React from "react"
import Link from "next/link"
import { Terminal, ArrowLeft } from "lucide-react"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border/40 bg-background/80 backdrop-blur-md">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="bg-primary/10 text-primary p-1.5 rounded-md">
              <Terminal size={18} strokeWidth={2.5} />
            </div>
            <span className="font-bold tracking-tight text-lg">Marscoder</span>
          </Link>
          <Link href="/" className="text-sm font-medium text-muted-foreground hover:text-foreground flex items-center">
            <ArrowLeft className="w-4 h-4 mr-1" /> Back to Home
          </Link>
        </div>
      </header>

      <main className="container mx-auto px-4 py-16 max-w-3xl">
        <div className="mb-10">
          <h1 className="text-4xl font-bold tracking-tight mb-4">Terms of Service</h1>
          <p className="text-muted-foreground">Last updated: May 3, 2026</p>
        </div>

        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6">
          <section>
            <h2 className="text-2xl font-bold mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Marscoder ("the Service"), you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">2. Service Description</h2>
            <p>
              Marscoder provides an AI-powered software development platform. The Service includes autonomous agents, development environments, and related API infrastructure. We reserve the right to modify, suspend, or discontinue any part of the Service at any time.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">3. User Responsibilities</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Generate malicious code, malware, or systems designed to compromise security.</li>
              <li>Violate any applicable laws, intellectual property rights, or third-party rights.</li>
              <li>Attempt to bypass, disable, or interfere with security-related features of the Service.</li>
              <li>Use the Service to build a competitive product or service using our proprietary models.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">4. Intellectual Property Rights</h2>
            <p>
              <strong>You retain all ownership rights</strong> to the code, software, and applications generated by Marscoder within your private workspaces. Marscoder claims no copyright or ownership over the final software products you build using our AI agents.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">5. Limitation of Liability</h2>
            <p>
              In no event shall Marscoder, nor its directors, employees, or partners, be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or use, resulting from your access to or use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">6. Termination</h2>
            <p>
              We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever, including without limitation if you breach the Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-3">7. Contact</h2>
            <p>
              For legal inquiries regarding these Terms, please contact us at <a href="mailto:legal@marscoder.com" className="text-primary hover:underline">legal@marscoder.com</a>.
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}
